---
postgresql_python_library: python3-psycopg2
postgresql_locales:
  - 'en_US.UTF-8'
  - 'ru_RU.UTF-8'
postgresql_hba_entries:
  - type: local
    database: all
    user: postgres
    auth_method: peer
  - type: local
    database: all
    user: all
    auth_method: peer
  - type: host
    database: all
    user: all
    address: '0.0.0.0/0'
    auth_method: "md5"
postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'
  - option: log_directory
    value: 'log'
  - option: listen_addresses
    value: '0.0.0.0'
